# Copyright (c) 2026 Tencent Inc.
# SPDX-License-Identifier: Apache-2.0

"""E2E coverage for network.rules with custom L7 ports (feat/custom_l7_port).

The custom L7 port feature lets an egress rule pin the TCP port CubeEgress
intercepts on, via ``Match.port`` + ``Match.scheme``. This module exercises:

  1. Custom HTTP port interception + credential injection — a rule with
     ``(host, port, scheme=http)`` redirects a non-standard sandbox egress
     port through CubeEgress and injects the rule's ``Inject`` header; the
     upstream echo response reflects the marker back to the sandbox.
  2. Backward-compatible scheme-only rule — ``Match`` with ``scheme`` but no
     ``port`` still intercepts the classic default set (``:80``/``:443``) and
     injects on ``:80``.
  3. Create-time rejection of ``port`` without ``scheme`` (SDK ValueError).
  4. Create-time rejection of a subnet-CIDR ``host`` (server-side policy error).

Topology notes
--------------
* The custom-port leg runs a tiny HTTP echo server **in the test process** and
  points the sandbox egress at ``SDK_E2E_L7_TARGET_HOST`` (a host IP reachable
  from sandboxes, e.g. the bridge the sandbox pod attaches to). Set that env var
  or the test is skipped — there is no portable default for "an IP the sandbox
  can reach that is not the node IP".
* Plaintext HTTP legs are used on purpose: they need no TLS interception CA, so
  they pass in any cluster that runs CubeEgress. The public :80 leg is resolved
  by the test host and pinned with curl ``--resolve`` so guest DNS learning is
  tested independently in ``test_dns_allow.py``.
* HTTPS custom-port legs require the sandbox image to trust the interception CA
  and are also covered by
  ``examples/code-sandbox-quickstart/network_l7_custom_port_echo.py``.
* All probing is done *inside* the sandbox via ``curl``; we grep the echoed
  response for the injected marker secret.
"""

from __future__ import annotations

import ipaddress
import json
import os
import shlex
import socket
import threading
import time
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse

import pytest
from adapters import create_adapter
from framework.assertions import assert_command_ok
from framework.capabilities import NETWORK_L7_CUSTOM_PORT, capabilities_for_backend
from framework.cleanup import safe_kill
from framework.config import SdkE2EConfig

# Host the sandbox can reach for the custom-port egress leg. Required; the test
# skips when unset (no safe portable default — see module docstring).
L7_TARGET_HOST = os.environ.get("SDK_E2E_L7_TARGET_HOST")
# Custom plaintext HTTP port the echo server listens on (+ the rule pins).
# 0 = let the OS assign a free port. A fixed default can collide with a
# leftover echo server from an interrupted run (EADDRINUSE); overriding via
# SDK_E2E_L7_CUSTOM_HTTP_PORT is still possible when a fixed port is required.
L7_CUSTOM_HTTP_PORT = int(os.environ.get("SDK_E2E_L7_CUSTOM_HTTP_PORT", "0"))
# Public host for the scheme-only default-set leg (echoes request headers).
L7_DEFAULT_HOST = os.environ.get("SDK_E2E_L7_DEFAULT_HOST", "httpbingo.org")
L7_MARKER_HEADER = "X-Cube-L7-E2E"
# Per-session unique secret so the grep cannot match ambient traffic.
L7_MARKER_SECRET = f"e2e-{uuid.uuid4().hex[:12]}"

# HTTPS custom-port leg. TLS MITM means the sandbox image must trust the L7
# interception CA (same prerequisite as the SDK quickstart example). There is no
# portable default for "a publicly-signed HTTPS endpoint on a non-standard
# port whose upstream cert CubeEgress can verify", so the URL is configurable
# and the whole leg is skipped unless the CA-trust prerequisite is declared.
L7_CUSTOM_HTTPS_URL = os.environ.get(
    "SDK_E2E_L7_CUSTOM_HTTPS_URL", "https://tls-v1-2.badssl.com:1012/"
)
_l7_https = urlparse(L7_CUSTOM_HTTPS_URL)
L7_CUSTOM_HTTPS_HOST = _l7_https.hostname
L7_CUSTOM_HTTPS_PORT = _l7_https.port  # None when the URL omits the port
L7_HTTPS_CAP_TRUSTED = os.environ.get("SDK_E2E_L7_HTTPS_CAP_TRUSTED", "").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}
# Subject CN of the cluster's MITM interception CA (generated by
# deploy/one-click .../cube-egress-prepare.sh as "CubeSandbox Egress MITM CA").
# An intercepted TLS connection is terminated by a leaf cert issued by this CA;
# a plain-SNAT passthrough would present the upstream's real publicly-issued
# cert instead. Asserting the leaf issuer proves interception actually happened.
L7_INTERCEPTION_ISSUER = os.environ.get(
    "SDK_E2E_L7_INTERCEPTION_ISSUER", "CubeSandbox Egress MITM CA"
)

pytestmark = [
    pytest.mark.e2e,
    pytest.mark.sdk_compat,
    pytest.mark.network,
    pytest.mark.p1,
]


def _skip_without_capability(sdk_backend: str) -> None:
    if NETWORK_L7_CUSTOM_PORT not in capabilities_for_backend(sdk_backend):
        pytest.skip(
            f"backend {sdk_backend!r} does not support {NETWORK_L7_CUSTOM_PORT}"
        )


class _HeaderEchoHandler(BaseHTTPRequestHandler):
    def do_GET(self) -> None:  # noqa: N802
        payload = json.dumps(
            {"path": self.path, "headers": dict(self.headers)}
        ).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, *_args: object) -> None:
        pass


def _detect_bridge_ip() -> str | None:
    """Best-effort mirror of the example's detect_target_host() for local runs.

    Only used as a fallback when SDK_E2E_L7_TARGET_HOST is unset; the test still
    skips unless the caller sets the env var (we never assume reachability).
    """
    try:
        out = (
            __import__("subprocess")
            .check_output(["ip", "-4", "-o", "addr", "show", "up"], text=True)
        )
        for line in out.splitlines():
            parts = line.split()
            if len(parts) >= 4 and parts[1].startswith(("docker", "br-")):
                return parts[3].split("/")[0]
    except Exception:
        pass
    return None


@pytest.fixture(scope="module")
def l7_echo_server():
    """Start the in-process HTTP echo server for the custom-port leg.

    Skips the dependant test when no reachable target host is configured, so we
    never bind a port or run a sandbox in environments that can't route to it.
    """
    if not L7_TARGET_HOST and not _detect_bridge_ip():
        pytest.skip(
            "SDK_E2E_L7_TARGET_HOST is required for the custom L7 port egress "
            "leg (a host IP reachable from sandboxes)"
        )
    server = ThreadingHTTPServer(("0.0.0.0", L7_CUSTOM_HTTP_PORT), _HeaderEchoHandler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        # server.server_address[1] is the OS-assigned port when
        # L7_CUSTOM_HTTP_PORT == 0 (the default).
        yield L7_TARGET_HOST or _detect_bridge_ip(), server.server_address[1]
    finally:
        server.shutdown()
        server.server_close()


def _l7_rules_custom_http(target_host: str, port: int) -> list[dict]:
    return [
        {
            "name": "e2e-custom-http",
            "match": {
                "host": target_host,
                "port": port,
                "scheme": "http",
            },
            "action": {
                "allow": True,
                "inject": [{"header": L7_MARKER_HEADER, "secret": L7_MARKER_SECRET}],
            },
        }
    ]


def _l7_rules_scheme_only_default(target_ips: tuple[str, ...]) -> list[dict]:
    rules = [
        {
            "name": "e2e-default-http",
            "match": {"host": L7_DEFAULT_HOST, "scheme": "http"},
            "action": {
                "allow": True,
                "inject": [{"header": L7_MARKER_HEADER, "secret": L7_MARKER_SECRET}],
            },
        }
    ]
    rules.extend(
        {
            "name": f"e2e-default-http-transport-{index}",
            "match": {"host": target_ip, "scheme": "http"},
            "action": {"allow": True},
        }
        for index, target_ip in enumerate(target_ips)
        if target_ip != L7_DEFAULT_HOST
    )
    return rules


def _resolve_default_host_ipv4(attempts: int = 3) -> tuple[str, ...]:
    try:
        address = ipaddress.IPv4Address(L7_DEFAULT_HOST)
        addresses = (address,)
    except ipaddress.AddressValueError:
        for attempt in range(attempts):
            try:
                addrinfo = socket.getaddrinfo(
                    L7_DEFAULT_HOST, 80, family=socket.AF_INET, type=socket.SOCK_STREAM
                )
                break
            except socket.gaierror as exc:
                if attempt + 1 == attempts:
                    raise RuntimeError(
                        f"failed to resolve IPv4 addresses for {L7_DEFAULT_HOST!r}"
                    ) from exc
                time.sleep(min(2**attempt, 5))
        addresses = tuple(
            dict.fromkeys(
                ipaddress.IPv4Address(sockaddr[0])
                for family, _, _, _, sockaddr in addrinfo
                if family == socket.AF_INET
            )
        )
    if not addresses:
        raise RuntimeError(f"no IPv4 address found for {L7_DEFAULT_HOST!r}")
    if any(not address.is_global for address in addresses):
        raise RuntimeError(f"non-public IPv4 address found for {L7_DEFAULT_HOST!r}")
    return tuple(map(str, addresses))


def _scheme_only_curl_command(target_ips: tuple[str, ...]) -> str:
    addresses = ",".join(target_ips)
    resolve = shlex.quote(f"{L7_DEFAULT_HOST}:80:{addresses}")
    url = shlex.quote(f"http://{L7_DEFAULT_HOST}/headers")
    return (
        f"curl -sS --connect-timeout 5 --max-time 8 --retry 2 "
        f"--retry-delay 1 --retry-max-time 25 --retry-all-errors "
        f"--resolve {resolve} {url}"
    )


@pytest.mark.framework
def test_scheme_only_probe_uses_all_resolved_public_ipv4(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr("test_l7_custom_port.L7_DEFAULT_HOST", "example.com")
    monkeypatch.setattr(
        socket,
        "getaddrinfo",
        lambda *_args, **_kwargs: [
            (socket.AF_INET, socket.SOCK_STREAM, 6, "", ("93.184.216.35", 80)),
            (socket.AF_INET, socket.SOCK_STREAM, 6, "", ("93.184.216.34", 80)),
            (socket.AF_INET, socket.SOCK_STREAM, 6, "", ("93.184.216.35", 80)),
        ],
    )

    target_ips = _resolve_default_host_ipv4()

    assert target_ips == ("93.184.216.35", "93.184.216.34")
    assert [
        rule["match"]["host"] for rule in _l7_rules_scheme_only_default(target_ips)
    ] == [L7_DEFAULT_HOST, *target_ips]
    command = _scheme_only_curl_command(target_ips)
    assert f"{L7_DEFAULT_HOST}:80:{','.join(target_ips)}" in command
    assert "--retry-max-time 25" in command


@pytest.mark.framework
def test_scheme_only_probe_rejects_non_public_ipv4(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr("test_l7_custom_port.L7_DEFAULT_HOST", "example.com")
    monkeypatch.setattr(
        socket,
        "getaddrinfo",
        lambda *_args, **_kwargs: [
            (socket.AF_INET, socket.SOCK_STREAM, 6, "", ("127.0.0.1", 80))
        ],
    )

    with pytest.raises(RuntimeError, match="non-public IPv4"):
        _resolve_default_host_ipv4()


@pytest.mark.framework
def test_scheme_only_probe_retries_resolution(monkeypatch: pytest.MonkeyPatch) -> None:
    attempts = iter(
        [
            socket.gaierror("temporary failure"),
            [(socket.AF_INET, socket.SOCK_STREAM, 6, "", ("93.184.216.34", 80))],
        ]
    )

    def resolve(*_args, **_kwargs):
        result = next(attempts)
        if isinstance(result, Exception):
            raise result
        return result

    monkeypatch.setattr("test_l7_custom_port.L7_DEFAULT_HOST", "example.com")
    monkeypatch.setattr(socket, "getaddrinfo", resolve)
    monkeypatch.setattr(time, "sleep", lambda _delay: None)

    assert _resolve_default_host_ipv4() == ("93.184.216.34",)


def _l7_rules_custom_https(host: str, port: int) -> list[dict]:
    return [
        {
            "name": "e2e-custom-https",
            "match": {"host": host, "port": port, "scheme": "https"},
            "action": {"allow": True},
        }
    ]


@pytest.mark.requires_capability(NETWORK_L7_CUSTOM_PORT)
def test_l7_custom_port_injects_marker_on_custom_http_port(
    sdk_backend: str,
    sdk_e2e_config: SdkE2EConfig,
    l7_echo_server: tuple[str, int],
):
    """A (host, port, scheme=http) rule intercepts a non-standard egress port
    and injects the rule's credential header; the echo reflects it back."""
    _skip_without_capability(sdk_backend)
    target_host, http_port = l7_echo_server

    adapter = None
    try:
        adapter = create_adapter(
            sdk_backend,
            sdk_e2e_config,
            metadata={
                "test_suite": "sdk_compat",
                "test_backend": sdk_backend,
                "test_case": "l7_custom_port_injects_marker",
            },
            create_options={
                "allow_internet_access": False,
                "network": {"rules": _l7_rules_custom_http(target_host, http_port)},
            },
        )

        url = f"http://{target_host}:{http_port}/headers"
        result = adapter.run_command(
            f"curl -sS --max-time 20 '{url}'",
            timeout=sdk_e2e_config.command_timeout,
        )
        assert_command_ok(result)
        assert L7_MARKER_SECRET in result.stdout, (
            f"custom-port L7 rule should inject {L7_MARKER_HEADER!r} at {url}; "
            f"response={result.stdout[:400]!r} stderr={result.stderr[:200]!r}"
        )
    finally:
        if adapter is not None:
            safe_kill(adapter, sdk_e2e_config)


@pytest.mark.requires_capability(NETWORK_L7_CUSTOM_PORT)
@pytest.mark.requires_internet
def test_l7_custom_port_scheme_only_intercepts_default_http_set(
    sdk_backend: str,
    sdk_e2e_config: SdkE2EConfig,
):
    """A scheme-only rule (no port) keeps the classic :80 default behavior and
    still injects on the default HTTP port — backward compatibility."""
    _skip_without_capability(sdk_backend)

    target_ips = _resolve_default_host_ipv4()
    adapter = None
    try:
        adapter = create_adapter(
            sdk_backend,
            sdk_e2e_config,
            metadata={
                "test_suite": "sdk_compat",
                "test_backend": sdk_backend,
                "test_case": "l7_custom_port_scheme_only_default",
            },
            create_options={
                "allow_internet_access": False,
                "network": {"rules": _l7_rules_scheme_only_default(target_ips)},
            },
        )

        url = f"http://{L7_DEFAULT_HOST}/headers"
        result = adapter.run_command(
            _scheme_only_curl_command(target_ips),
            timeout=sdk_e2e_config.command_timeout,
        )
        assert_command_ok(result)
        assert L7_MARKER_SECRET in result.stdout, (
            f"scheme-only L7 rule should intercept :80 and inject "
            f"{L7_MARKER_HEADER!r} at {url}; response={result.stdout[:400]!r} "
            f"stderr={result.stderr[:200]!r}"
        )
    finally:
        if adapter is not None:
            safe_kill(adapter, sdk_e2e_config)


@pytest.mark.requires_capability(NETWORK_L7_CUSTOM_PORT)
def test_l7_custom_port_rejects_port_without_scheme(
    sdk_backend: str,
    sdk_e2e_config: SdkE2EConfig,
):
    """Match.port requires Match.scheme — the SDK raises ValueError before any
    network round-trip (mirrors Match.__post_init__ / _normalize_match_dict)."""
    _skip_without_capability(sdk_backend)

    adapter = None
    try:
        with pytest.raises(Exception) as exc_info:
            adapter = create_adapter(
                sdk_backend,
                sdk_e2e_config,
                metadata={
                    "test_suite": "sdk_compat",
                    "test_backend": sdk_backend,
                    "test_case": "l7_custom_port_port_without_scheme",
                },
                create_options={
                    "network": {
                        "rules": [
                            {
                                "name": "bad-port-no-scheme",
                                "match": {"host": "198.51.100.7", "port": 1234},
                                "action": {"allow": True},
                            }
                        ]
                    }
                },
            )
        message = str(exc_info.value).lower()
        assert "port" in message and "scheme" in message, (
            f"create failure should mention the port/scheme pairing constraint; "
            f"got={exc_info.value!r}"
        )
    finally:
        if adapter is not None:
            safe_kill(adapter, sdk_e2e_config)


@pytest.mark.requires_capability(NETWORK_L7_CUSTOM_PORT)
def test_l7_custom_port_rejects_subnet_host(
    sdk_backend: str,
    sdk_e2e_config: SdkE2EConfig,
):
    """An L7 rule host must be a single host IP or a domain — a subnet CIDR is
    rejected server-side (cubevs netpolicy: subnet CIDR not supported for L7)."""
    _skip_without_capability(sdk_backend)

    adapter = None
    try:
        with pytest.raises(Exception) as exc_info:
            adapter = create_adapter(
                sdk_backend,
                sdk_e2e_config,
                metadata={
                    "test_suite": "sdk_compat",
                    "test_backend": sdk_backend,
                    "test_case": "l7_custom_port_subnet_host",
                },
                create_options={
                    "network": {
                        "rules": [
                            {
                                "name": "bad-subnet-host",
                                "match": {
                                    "host": "10.0.0.0/24",
                                    "scheme": "http",
                                },
                                "action": {"allow": True},
                            }
                        ]
                    }
                },
            )
        message = str(exc_info.value).lower()
        assert "subnet" in message or "cidr" in message or "host" in message, (
            f"create failure should mention the subnet/host constraint; "
            f"got={exc_info.value!r}"
        )
    finally:
        if adapter is not None:
            safe_kill(adapter, sdk_e2e_config)


def _fetch_leaf_issuer(adapter, sdk_e2e_config, attempts: int = 3) -> str:
    """Return the issuer of the TLS leaf cert the sandbox is presented with.

    Uses ``openssl s_client`` (no verification, so the handshake completes even
    for the interception CA) and extracts the leaf issuer via ``openssl x509``.
    An intercepted connection shows the cluster interception CA; a plain-SNAT
    passthrough shows the upstream's real public CA.

    Retries when the handshake fails to produce a cert (transient connect/timeout
    against the public endpoint), so a slow upstream does not flake the leg.
    """
    cmd = (
        f"openssl s_client -connect {L7_CUSTOM_HTTPS_HOST}:{L7_CUSTOM_HTTPS_PORT} "
        f"-servername {L7_CUSTOM_HTTPS_HOST} </dev/null 2>/dev/null "
        f"| openssl x509 -noout -issuer"
    )
    out = ""
    for attempt in range(attempts):
        result = adapter.run_command(cmd, timeout=sdk_e2e_config.command_timeout)
        assert_command_ok(result)
        out = result.stdout.strip()
        if out:
            return out
        if attempt + 1 < attempts:
            time.sleep(min(2 ** attempt, 5))
    return out


@pytest.mark.requires_capability(NETWORK_L7_CUSTOM_PORT)
@pytest.mark.requires_internet
def test_l7_custom_port_https_intercepts_custom_port(
    sdk_backend: str,
    sdk_e2e_config: SdkE2EConfig,
):
    """A (host, port, scheme=https) rule intercepts a non-standard HTTPS egress
    port: CubeEgress does TLS MITM and forwards to the upstream. Proves the
    port-scoped scheme=https interception path on a non-443 port.

    Interception is proven by asserting the TLS leaf issuer: an intercepted
    connection is terminated by CubeEgress's MITM cert, issued by the cluster
    interception CA (L7_INTERCEPTION_ISSUER), whereas a plain-SNAT passthrough
    would present the upstream's real publicly-issued cert. This distinguishes
    interception from mere reachability — a bare 200/body check could not.
    """
    _skip_without_capability(sdk_backend)
    if not L7_HTTPS_CAP_TRUSTED:
        pytest.skip(
            "HTTPS L7 interception needs the sandbox image to trust the L7 "
            "interception CA; set SDK_E2E_L7_HTTPS_CAP_TRUSTED=1 to enable "
            "(see examples/code-sandbox-quickstart/network_l7_custom_port_echo.py)"
        )
    if not L7_CUSTOM_HTTPS_HOST or not L7_CUSTOM_HTTPS_PORT:
        pytest.skip(
            f"SDK_E2E_L7_CUSTOM_HTTPS_URL must include an explicit port; "
            f"got {L7_CUSTOM_HTTPS_URL!r}"
        )
    if L7_CUSTOM_HTTPS_PORT == 443:
        pytest.skip(
            "HTTPS custom-port leg exercises a non-standard port; "
            f"{L7_CUSTOM_HTTPS_URL!r} resolves to :443 (use a non-443 port)"
        )

    adapter = None
    try:
        adapter = create_adapter(
            sdk_backend,
            sdk_e2e_config,
            metadata={
                "test_suite": "sdk_compat",
                "test_backend": sdk_backend,
                "test_case": "l7_custom_port_https_custom_port",
            },
            create_options={
                "allow_internet_access": False,
                "network": {
                    "rules": _l7_rules_custom_https(
                        L7_CUSTOM_HTTPS_HOST, L7_CUSTOM_HTTPS_PORT
                    )
                },
            },
        )

        result = adapter.run_command(
            f"curl -sS --connect-timeout 5 --max-time 8 --retry 2 "
            f"--retry-delay 1 --retry-max-time 25 --retry-all-errors "
            f"-o /dev/null -w 'code=%{{http_code}} len=%{{size_download}}' "
            f"{shlex.quote(L7_CUSTOM_HTTPS_URL)}",
            timeout=sdk_e2e_config.command_timeout,
        )
        assert_command_ok(result)
        out = result.stdout.strip()
        assert "code=200" in out, (
            f"custom-port HTTPS L7 rule should proxy {L7_CUSTOM_HTTPS_URL} to "
            f"HTTP 200; curl output={out!r} stderr={result.stderr[:200]!r}"
        )
        assert "len=0" not in out, (
            f"custom-port HTTPS L7 rule proxied {L7_CUSTOM_HTTPS_URL} but the "
            f"upstream returned an empty body; curl output={out!r}"
        )

        # The 200/body check above only proves reachability. Assert the TLS
        # leaf was issued by the interception CA to prove the connection was
        # actually MITM-intercepted (not plain-SNAT passthrough, which would
        # present the upstream's real public CA).
        issuer = _fetch_leaf_issuer(adapter, sdk_e2e_config)
        assert L7_INTERCEPTION_ISSUER in issuer, (
            f"expected interception CA {L7_INTERCEPTION_ISSUER!r} as the TLS "
            f"leaf issuer (proves MITM interception); got issuer={issuer!r}. "
            f"A public CA here means the custom-port HTTPS flow bypassed "
            f"CubeEgress (plain SNAT passthrough)."
        )
    finally:
        if adapter is not None:
            safe_kill(adapter, sdk_e2e_config)
